<?php


namespace App\Enums;

enum DomainError: string
{
    case INVALID_ACCOUNT_NUMBER  = 'INVALID_ACCOUNT_NUMBER';
    case INVALID_INITIAL_BALANCE = 'INVALID_INITIAL_BALANCE';
    case ACCOUNT_ALREADY_EXISTS  = 'ACCOUNT_ALREADY_EXISTS';
    case ACCOUNT_NOT_FOUND       = 'ACCOUNT_NOT_FOUND';
    case INVALID_DEPOSIT_AMOUNT  = 'INVALID_DEPOSIT_AMOUNT';
    case INVALID_WITHDRAW_AMOUNT = 'INVALID_WITHDRAW_AMOUNT';
    case INSUFFICIENT_FUNDS      = 'INSUFFICIENT_FUNDS';
    case INTERNAL_ERROR          = 'INTERNAL_ERROR';
}
